demosite = "https://github.com/"
description = "Theme for Grid Fly LLC."
features = [
  "accessibility",
  "analytics",
  "bootstrap styles and icons",
  "dark color scheme",
  "image thumbnails",
  "landing page",
  "languages",
]
homepage = "https://github.com/mccarthyhayden/gridfly-theme"
license = "MIT"
licenselink = "https://github.com/mccarthyhayden/gridfly-theme/LICENSE"
name = "Grid Fly Theme"
tags = [
  "bootstrap",
  "company",
  "dark",
  "gallery",
  "hero",
  "landing",
  "light",
  "multilingual",
  "responsive",
]

[author]
homepage = "https://gridfly.us"
name = "Hayden McCarthy"
